# Generated by Django 6.0.4 on 2026-05-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_quantity'),
        ('donates', '0002_donate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='choice_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='выберите блог для покупки'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ваше фио'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='number_card',
            field=models.PositiveIntegerField(default='41695853'),
        ),
    ]
