# Generated by Django 6.0.4 on 2026-05-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_categorycar_car_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nummercar',
            name='choice_car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_car', to='auto.car'),
        ),
    ]
